[default]
src = 'contracts'
out = 'out'
libs = ['node_modules']
remappings = [
    '@ensdomains/=node_modules/@ensdomains/',
    'hardhat/=node_modules/hardhat/',
    'ds-test/=lib/ds-test/src/',
    '@openzeppelin=lib/openzeppelin-contracts/contracts/',
]

# See more config options https://github.com/gakonst/foundry/tree/master/config