import type { NextPage } from 'next'
import Link from 'next/link'
import Head from 'next/head'
import Image from 'next/image'
import style from '../styles/Home.module.css'
import Navbar from '../components/external/Navbar'
import Footer from '../components/external/Footer'

const Dao: NextPage = () => {
  return (
    <div className={style.Daoheader}>
      <Navbar />
      <header className={style.DaoContainer}>
        <h1>Ready to experience the reinvention of energy systems?</h1>
      </header>
      <Link href="/">
        <a className={style.link9}>
          <span>Launch DAO</span>
          <hr className={style.sec_hr9} />
        </a>
      </Link>
      <div className={style.dome}>
        <Image src="/dome2.png" height="300.88px" width="837.8px" />
      </div>

      <section className={style.bg_daoContainer}>
        <div className={style.h3_bg_daoContainer}>
          <h3>Welcome to the Kayce DAO</h3>
        </div>
        <hr />
        <div className={style.mini_bg_daoContainer}>
          <p>
            DAOs (Decentralized Autonomous Organisations) are digital
            structures, that make it possible for like minded people to safely
            collaborate and coordinate on a global scale. They are collectively
            owned and managed by their members. Decisions are governed by
            members writing proposals, and voting to ensure everyone in the
            organisation has a voice.
          </p>
        </div>
      </section>
      <div className={style.pg_across}>
        <Image src="/Group154.png" height="146.88px" width="1450px" />
      </div>
      <section className={style.bg_across_container}>
        <div className={style.sm_across}>
          <Image src="/Group156.png" height="732.85px" width="393px" />
        </div>
        <div className={style.sm_across_container}>
          <h3>HOW IT WORKS</h3>
          <h2>
            The Kayce DAO ecosystem is community-governed, decentralized, and
            circular by design.
          </h2>
          <p>
            Members of the public can join VitaDAO and govern its IP through
            VITA tokens by contributing funds, work, or valuable research data
            or IP assets. VITA tokens enable their holder to engage in
            decision-making and governance of VitaDAO’s research, signal support
            for specific initiatives, and govern its data repositories and IP
            portfolio.
          </p>
          <hr />
          <h3>PORTFOLIO STRUCTURE</h3>
          <p>
            VitaDAO will acquire and commission research, as well as own,
            develop and monetize the resulting intellectual property assets. Our
            portfolio consists of:
          </p>
          <p>
            1. NFTs representing intellectual property, patents and licenses to
            therapeutic research projects.
          </p>
          <p>
            2. Data assets generated by funding R&D around its research projects
            and NFTs.
          </p>
          <p>
            To fund more research and to provide long term funding for the DAO
            operations, there are several options to monetize owned data and IP
          </p>
          <hr />
          <h3>PROJECT ENGAGEMENT</h3>
          <p>
            Vetted longevity research projects will request funds from VitaDAO,
            and members will vote to grant or raise those funds in exchange for
            ownership in the resulting IP.
          </p>
          <p>
            VitaDAO can enter co-development deals with private companies or
            other DAOs. In single or multi-license agreements, VitaDAO could
            license data and IP to 3rd parties, or could sell to the highest
            suitable bidder. One route of IP monetisation would be data
            marketplaces, where VitaDAO can securely publish selected parts of
            the research data or findings.
          </p>
        </div>
      </section>
      <section className={style.bg_summary_container}>
        <h3>KAYCE DAO SUMMARY </h3>
        <div className={style.main_summary_container}>
          <div>
            <p>35+ projects evaluated and funded</p>
          </div>
          <div>
            <p>Over 2000 members across 23 countries</p>
          </div>
          <div>
            <p>$25 - 500k ticket size for project financing</p>
          </div>
        </div>
      </section>
      <section className={style.empty_container_bg}></section>
      <section className={style.empty_container}>
        <div className={style.empty_container_img}>
          <h1>Governance</h1>
          <div className={style.colors}>
            <Image src="/Group6.png" height="253px" width="510.64px" />
          </div>
        </div>
        <div className={style.empty_container_sm}>
          <p>
            The Kayce DAO governance token ($KAYCE) is the cryptocurrency token
            that offers a wide range of utility and benefits within the
            organization. $KAYCE fuels crypto transactions, automatic
            investments, and so much more.
          </p>
          <h3>TOTAL TOKEN SUPPLY</h3>
          <h2>
            1,000,000,000<span>KAYCE</span>
          </h2>
          <h3>PUBLIC SALE HARDCAP</h3>
          <h2>$600,000</h2>
          <h3>PUBLIC SALE TOKEN PRICE</h3>
          <h2>$0.15</h2>
          <hr />
        </div>
      </section>
      <section className={style.active_container_sm}>
        <div className={style.active_container_bg}>
          <h3>
            An active team, community of contributors and partners are the
            driving force behind our success
          </h3>
          <Link href="/">
            <a className={style.link0}>
              <span>Join the Community</span>
              <hr className={style.sec_hr0} />
            </a>
          </Link>
        </div>
        <div className={style.active_container_main_main}>
          <div className={style.active_container_main}>
            <div className={style.active_container_main_bg}>
              <div className={style.colors1}>
                <Image src="/portfolio.png" height="122px" width="123px" />
              </div>
              <p className={style.colors_p}>John Doe</p>
              <p>
                PhD Candidate at UNSW Medicine. Focus on Fertility Preservation.
                On Deck Longevity Fellow.
              </p>
              <div className={style.active_container_main_sm}>
                <div className={style.colors1}>
                  <Image src="/smtwitter.png" height="9px" width="10px" />
                </div>
                <div className={style.colors1}>
                  <Image src="/smlinkedin.png" height="10px" width="9px" />
                </div>
                <div className={style.colors1}>
                  <Image src="/Arrow13.png" height="9.9px" width="9.9px" />
                </div>
              </div>
              <hr />
            </div>
            <div className={style.active_container_main_bg}>
              <div className={style.colors1}>
                <Image src="/portfolio.png" height="122px" width="123px" />
              </div>
              <p className={style.colors_p}>John Doe</p>
              <p>
                PhD Candidate at UNSW Medicine. Focus on Fertility Preservation.
                On Deck Longevity Fellow.
              </p>
              <div className={style.active_container_main_sm}>
                <div className={style.colors1}>
                  <Image src="/smtwitter.png" height="9px" width="10px" />
                </div>
                <div className={style.colors1}>
                  <Image src="/smlinkedin.png" height="10px" width="9px" />
                </div>
                <div className={style.colors1}>
                  <Image src="/Arrow13.png" height="9.9px" width="9.9px" />
                </div>
              </div>
              <hr />
            </div>
            <div className={style.active_container_main_bg}>
              <div className={style.colors1}>
                <Image src="/portfolio.png" height="122px" width="123px" />
              </div>
              <p className={style.colors_p}>John Doe</p>
              <p>
                PhD Candidate at UNSW Medicine. Focus on Fertility Preservation.
                On Deck Longevity Fellow.
              </p>
              <div className={style.active_container_main_sm}>
                <div className={style.colors1}>
                  <Image src="/smtwitter.png" height="9px" width="10px" />
                </div>
                <div className={style.colors1}>
                  <Image src="/smlinkedin.png" height="10px" width="9px" />
                </div>
                <div className={style.colors1}>
                  <Image src="/Arrow13.png" height="9.9px" width="9.9px" />
                </div>
              </div>
              <hr />
            </div>
            <div className={style.active_container_main_bg}>
              <div className={style.colors1}>
                <Image src="/portfolio.png" height="122px" width="123px" />
              </div>
              <p className={style.colors_p}>John Doe</p>
              <p>
                PhD Candidate at UNSW Medicine. Focus on Fertility Preservation.
                On Deck Longevity Fellow.
              </p>
              <div className={style.active_container_main_sm}>
                <div className={style.colors1}>
                  <Image src="/smtwitter.png" height="9px" width="10px" />
                </div>
                <div className={style.colors1}>
                  <Image src="/smlinkedin.png" height="10px" width="9px" />
                </div>
                <div className={style.colors1}>
                  <Image src="/Arrow13.png" height="9.9px" width="9.9px" />
                </div>
              </div>
              <hr />
            </div>
          </div>
          <div className={style.active_container_main}>
            <div className={style.active_container_main_bg}>
              <div className={style.colors1}>
                <Image src="/portfolio.png" height="122px" width="123px" />
              </div>
              <p className={style.colors_p}>John Doe</p>
              <p>
                PhD Candidate at UNSW Medicine. Focus on Fertility Preservation.
                On Deck Longevity Fellow.
              </p>
              <div className={style.active_container_main_sm}>
                <div className={style.colors1}>
                  <Image src="/smtwitter.png" height="9px" width="10px" />
                </div>
                <div className={style.colors1}>
                  <Image src="/smlinkedin.png" height="10px" width="9px" />
                </div>
                <div className={style.colors1}>
                  <Image src="/Arrow13.png" height="9.9px" width="9.9px" />
                </div>
              </div>
              <hr />
            </div>
            <div className={style.active_container_main_bg}>
              <div className={style.colors1}>
                <Image src="/portfolio.png" height="122px" width="123px" />
              </div>
              <p className={style.colors_p}>John Doe</p>
              <p>
                PhD Candidate at UNSW Medicine. Focus on Fertility Preservation.
                On Deck Longevity Fellow.
              </p>
              <div className={style.active_container_main_sm}>
                <div className={style.colors1}>
                  <Image src="/smtwitter.png" height="9px" width="10px" />
                </div>
                <div className={style.colors1}>
                  <Image src="/smlinkedin.png" height="10px" width="9px" />
                </div>
                <div className={style.colors1}>
                  <Image src="/Arrow13.png" height="9.9px" width="9.9px" />
                </div>
              </div>
              <hr />
            </div>
            <div className={style.active_container_main_bg}>
              <div className={style.colors1}>
                <Image src="/portfolio.png" height="122px" width="123px" />
              </div>
              <p className={style.colors_p}>John Doe</p>
              <p>
                PhD Candidate at UNSW Medicine. Focus on Fertility Preservation.
                On Deck Longevity Fellow.
              </p>
              <div className={style.active_container_main_sm}>
                <div className={style.colors1}>
                  <Image src="/smtwitter.png" height="9px" width="10px" />
                </div>
                <div className={style.colors1}>
                  <Image src="/smlinkedin.png" height="10px" width="9px" />
                </div>
                <div className={style.colors1}>
                  <Image src="/Arrow13.png" height="9.9px" width="9.9px" />
                </div>
              </div>
              <hr />
            </div>
            <div className={style.active_container_main_bg}>
              <div className={style.colors1}>
                <Image src="/portfolio.png" height="122px" width="123px" />
              </div>
              <p className={style.colors_p}>John Doe</p>
              <p>
                PhD Candidate at UNSW Medicine. Focus on Fertility Preservation.
                On Deck Longevity Fellow.
              </p>
              <div className={style.active_container_main_sm}>
                <div className={style.colors1}>
                  <Image src="/smtwitter.png" height="9px" width="10px" />
                </div>
                <div className={style.colors1}>
                  <Image src="/smlinkedin.png" height="10px" width="9px" />
                </div>
                <div className={style.colors1}>
                  <Image src="/Arrow13.png" height="9.9px" width="9.9px" />
                </div>
              </div>
              <hr />
            </div>
          </div>
          <div className={style.active_container_main}>
            <div className={style.active_container_main_bg}>
              <div className={style.colors1}>
                <Image src="/portfolio.png" height="122px" width="123px" />
              </div>
              <p className={style.colors_p}>John Doe</p>
              <p>
                PhD Candidate at UNSW Medicine. Focus on Fertility Preservation.
                On Deck Longevity Fellow.
              </p>
              <div className={style.active_container_main_sm}>
                <div className={style.colors1}>
                  <Image src="/smtwitter.png" height="9px" width="10px" />
                </div>
                <div className={style.colors1}>
                  <Image src="/smlinkedin.png" height="10px" width="9px" />
                </div>
                <div className={style.colors1}>
                  <Image src="/Arrow13.png" height="9.9px" width="9.9px" />
                </div>
              </div>
              <hr />
            </div>
            <div className={style.active_container_main_bg}>
              <div className={style.colors1}>
                <Image src="/portfolio.png" height="122px" width="123px" />
              </div>
              <p className={style.colors_p}>John Doe</p>
              <p>
                PhD Candidate at UNSW Medicine. Focus on Fertility Preservation.
                On Deck Longevity Fellow.
              </p>
              <div className={style.active_container_main_sm}>
                <div className={style.colors1}>
                  <Image src="/smtwitter.png" height="9px" width="10px" />
                </div>
                <div className={style.colors1}>
                  <Image src="/smlinkedin.png" height="10px" width="9px" />
                </div>
                <div className={style.colors1}>
                  <Image src="/Arrow13.png" height="9.9px" width="9.9px" />
                </div>
              </div>
              <hr />
            </div>
            <div className={style.active_container_main_bg}>
              <div className={style.colors1}>
                <Image src="/portfolio.png" height="122px" width="123px" />
              </div>
              <p className={style.colors_p}>John Doe</p>
              <p>
                PhD Candidate at UNSW Medicine. Focus on Fertility Preservation.
                On Deck Longevity Fellow.
              </p>
              <div className={style.active_container_main_sm}>
                <div className={style.colors1}>
                  <Image src="/smtwitter.png" height="9px" width="10px" />
                </div>
                <div className={style.colors1}>
                  <Image src="/smlinkedin.png" height="10px" width="9px" />
                </div>
                <div className={style.colors1}>
                  <Image src="/Arrow13.png" height="9.9px" width="9.9px" />
                </div>
              </div>
              <hr />
            </div>
            <div className={style.active_container_main_bg}>
              <div className={style.colors1}>
                <Image src="/portfolio.png" height="122px" width="123px" />
              </div>
              <p className={style.colors_p}>John Doe</p>
              <p>
                PhD Candidate at UNSW Medicine. Focus on Fertility Preservation.
                On Deck Longevity Fellow.
              </p>
              <div className={style.active_container_main_sm}>
                <div className={style.colors1}>
                  <Image src="/smtwitter.png" height="9px" width="10px" />
                </div>
                <div className={style.colors1}>
                  <Image src="/smlinkedin.png" height="10px" width="9px" />
                </div>
                <div className={style.colors1}>
                  <Image src="/Arrow13.png" height="9.9px" width="9.9px" />
                </div>
              </div>
              <hr />
            </div>
          </div>
        </div>
      </section>
      <section className={style.active_latest_main_bg}>
        <div className={style.active_latest_bg}>
          <h3>
            LATEST <br />
            ANNOUNCEMENTS & INSIGHTS
          </h3>
          <div className={style.active_latest_mn}>
            <div className={style.active_latest_sm}>
              <div className={style.colors2}>
                <Image src="/Rectangle60.png" height="114px" width="134px" />
              </div>
              <div className={style.colors3}>
                <p className={style.colors4}>
                  Can we modify our immune cells to fix broken hearts 💔?
                  Journal Club S2 E9
                </p>
                <p>13th April, 2022.</p>
                <div className={style.active_latest_lt}>
                  <div className={style.active_latest_sm_button}>
                    <div className={style.active_latest_sm_buttonNews}>
                      <p>News</p>
                    </div>
                    <div className={style.active_latest_sm_buttonFinance}>
                      <p>Finance</p>
                    </div>
                  </div>
                  <div className={style.active_latest_gt}>
                    <div className={style.active_latest_sm_buttonDev}>
                      <p>Development</p>
                    </div>
                    <div className={style.active_latest_sm_linkbtn}>
                      <Link href="/">
                        <a>
                          <span>More</span>
                          <hr className={style.sec_hrq} />
                        </a>
                      </Link>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className={style.active_latest_sm}>
              <span className={style.colors_min}>
                <div className={style.colors2}>
                  <Image src="/Rectangle60.png" height="114px" width="134px" />
                </div>
              </span>
            </div>
          </div>
          <hr className={style.active_latest_hr} />
          <div className={style.active_latest_mn}>
            <div className={style.active_latest_sm}>
              <div className={style.colors2}>
                <Image src="/Rectangle60.png" height="114px" width="134px" />
              </div>
              <div className={style.colors3}>
                <p className={style.colors4}>
                  Can we modify our immune cells to fix broken hearts 💔?
                  Journal Club S2 E9
                </p>
                <p>13th April, 2022.</p>
              </div>
            </div>
            <div className={style.active_latest_sm}>
              <span className={style.colors_min}>
                <div className={style.colors2}>
                  <Image src="/Rectangle60.png" height="114px" width="134px" />
                </div>
              </span>
            </div>
          </div>
          <div className={style.main_colors2}>
            <div className={style.colors2}>
              <Image src="/Group138.png" height="26px" width="28px" />
            </div>
            <div className={style.colors2}>
              <Image src="/Group137.png" height="26px" width="28px" />
            </div>
          </div>
        </div>
        <div className={style.main_ctr_colors2}>
          <h1>UPCOMING EVENTS</h1>
          <div>
            <div className={style.main_colors3}>
              <div className={style.main_bg_colors2}>
                <p className={style.main_bg_colors2_p}>
                  Can we modify our immune cells to fix broken hearts 💔?
                  Journal Club S2 E9
                </p>
                <div className={style.colors3_container}>
                  <div className={style.colors3}>
                    <Image src="/location.png" height="16px" width="14px" />
                  </div>
                  <div className={style.main_sm_colors2}>
                    <p>Twitter Spaces</p>
                  </div>
                  <div className={style.colors3}>
                    <Image src="/calender.png" height="14px" width="13px" />
                  </div>
                  <div className={style.main_sm_colors2}>
                    <p>13th April, 2022.</p>
                  </div>
                  <div className={style.main_btn_colors2}>
                    <Link href="/">
                      <a className={style.link01}>
                        <span>Learn more</span>
                        <hr className={style.sec_hr01} />
                      </a>
                    </Link>
                  </div>
                </div>
              </div>
              <div className={style.main_bg_colors2}>
                <p className={style.main_bg_colors2_p}>
                  Can we modify our immune cells to fix broken hearts 💔?
                  Journal Club S2 E9
                </p>
                <div className={style.colors3_container}>
                  <div className={style.colors3}>
                    <Image src="/location.png" height="16px" width="14px" />
                  </div>
                  <div className={style.main_sm_colors2}>
                    <p>Twitter Spaces</p>
                  </div>
                  <div className={style.colors3}>
                    <Image src="/calender.png" height="14px" width="13px" />
                  </div>
                  <div className={style.main_sm_colors2}>
                    <p>13th April, 2022.</p>
                  </div>
                  <div className={style.main_btn_colors2}>
                    <Link href="/">
                      <a className={style.link01}>
                        <span>Learn more</span>
                        <hr className={style.sec_hr01} />
                      </a>
                    </Link>
                  </div>
                </div>
              </div>
              <div className={style.main_bg_colors9}></div>
            </div>
          </div>
        </div>
      </section>
      <section className={style.changing_world}>
        <div>
          <h1>Be a part of changing the world</h1>
          <p>
            Keep energy researches afloat with us as we build a future for
            context-based energy in emerging markets
          </p>
          <div className={style.changing_world_img}>
            <div>
              <Image src="/discord.png" height="46px" width="44px" />
            </div>
            <div>
              <Image src="/telegram.png" height="46px" width="44px" />
            </div>
            <div>
              <Image src="/medium.png" height="46px" width="44px" />
            </div>
            <div>
              <Image src="/youtube.png" height="46px" width="44px" />
            </div>
            <div>
              <Image src="/twitter.png" height="46px" width="44px" />
            </div>
          </div>
        </div>
      </section>
      <Footer/>
    </div>
  )
}

export default Dao
