import type { NextPage } from 'next'
import Link from 'next/link'
import Head from 'next/head'
import Image from 'next/image'
import style from '../styles/Home.module.css'
import Navbar from '../components/external/Navbar'
import Footer from '../components/external/Footer'

const Home: NextPage = () => {
  return (
    <div className={style.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <header className={style.header}>
        <div className={style.header_bg}>
          <h1>Accelerating the Energy Transition in Emerging Markets</h1>
          <p>
            <span className={style.edit}>Kayce [kəˈsē]</span> is a decentralized
            research and technology firm that aims to accelerate the energy
            transition in emerging markets by de-risking investments in
            contextualized energy projects.
          </p>
          <div className={style.main_link}>
            <Link href="/">
              <a className={style.link}>
                <span>Join the Community</span>
                <hr className={style.sec_hr} />
              </a>
            </Link>
            <Link href="/">
              <a className={style.link}>
                <span>Apply for Funding</span>
                <hr className={style.sec_hr} />
              </a>
            </Link>
          </div>
        </div>
      </header>
      <div className={style.overlay_div}>
        <Image src="/group.svg" height="134.44px" width="1444px" />
      </div>
      <main>
        <div className={style.main}>
          <h1>
            The future of energy is decentralised; the enabling infrastructure
            should be also{' '}
          </h1>
          <p>
            At Kayce, we discover and fund the most promising longevity research
            in a community collective manner. We are funding early stage energy
            research by de-risking and opening them up to all interested
            investors. Members can join KayceeDAO by purchasing Kaycee tokens or
            earning them through contributions of work or Intellectual Property.
          </p>
        </div>

        <div className={style.horizontal_image}>
          <Image src="/General.png" width="106.04px" height="521px" />
        </div>
        <div className={style.main_bg}>
          <div>
            <h1>
              We Provide
              <br />
              the Mindset Shift
            </h1>
          </div>
          <div className={style.main_bg_text}>
            <p>
              We believe the "One Size Fit All" approach to energy systems in
              emerging countries where there is little or no context about
              energy consumption behaviour and ideal socio technical interaction
              leads to poor investment considerations.
            </p>
            <hr className={style.min_hr} />
            <p>
              Kayce solves this problem by serving as the informant between VCs,
              consumer equity financing and others and creating decentralised
              banking models for these systems to enable emerging countries to
              leapfrog the energy transition.
            </p>
          </div>
        </div>
      </main>
      <section className={style.bg_section}>
        <span>WHAT WE DO</span>
        <div className={style.bg_section_big}>
          <div className={style.bg_section_arrow}>
            <div className={style.bg_section_small}>
              <h1>Financial services to power the energy tech revolution</h1>
              <p>
                We enable impact-verified investments in for energy sectors in
                emerging countries
              </p>
            </div>
            <div className={style.bg_section_pink}>
              <Image src="/pink.png" width="39.49px" height="37.13px" />
            </div>
          </div>
            <div className={style.earth_png}></div>
          <div className={style.bg_overlay}>
          </div>
        </div>
      </section>
      <hr className={style.sm_hr}/>
      <section className={style.sm_section}>
        <div className={style.sm_section_big}>
          <div className={style.sm_section_arrow}>
            <div className={style.sm_section_small}>
              <h1>World’s largest innovation challenge on green tech</h1>
              <p>
                We discover and fund the most promising energy systems research fit of emerging markets
              </p>
            </div>
            <div className={style.sm_section_pink}>
              <Image src="/grrenarrow.png" width="39.49px" height="37.13px" />
            </div>
          </div>
            <div className={style.earth_png}></div>
          <div className={style.sm_overlay}></div>
        </div>
      </section>
      <section className={style.bg_project}>
        <span>AT A GLANCE</span>
        <div className={style.sm_project}>
          <div>
            <h1>35+ projects evaluated and funded </h1>
          </div>
          <div>
            <h1>Over 2000 members across 23 countries</h1>
          </div>
          <div>
            <h1>$25 - 500k ticket size for project financing  </h1>
          </div>
        </div>
      </section>
      <section className={style.section_bg_partners}>
        <h1>Our Companies and Partners</h1>
        <div className={style.bg_partner}>
          <div className={style.partner}>
            <div>
              <div className={style.arow}>
                <Image className={style.move} src='/a.png' width='85px' height='97px'/>
              </div>
              <p className={style.sm_para}>Scheibye-Knudsen Lab </p>
              <p className={style.para}>Research Partner</p>
              <div className={style.arrow_left}>
                <Image src='/earrow.png' width='15px' height='15px'/>
              </div>
              <hr className={style.bm_hr}/>
            </div>
          </div>
          <div className={style.partner}>
            <div className={style.com_div}>
              <div className={style.arow}>
                <Image className={style.move} src='/b.png' width='85px' height='97px'/>
              </div>
              <p className={style.sm_para}>Scheibye-Knudsen Lab </p>
              <p className={style.para}>Research Partner</p>
              <div className={style.arrow_left}>
                <Image src='/earrow.png' width='15px' height='15px'/>
              </div>
              <hr className={style.bm_hr}/>
            </div>
          </div>
          <div className={style.partner}>
            <div>
              <div className={style.arow}>
                <Image className={style.move} src='/a.png' width='85px' height='97px'/>
              </div>
              <p className={style.sm_para}>Scheibye-Knudsen Lab </p>
              <p className={style.para}>Research Partner</p>
              <div className={style.arrow_left}>
                <Image src='/earrow.png' width='15px' height='15px'/>
              </div>
              <hr className={style.bm_hr}/>
            </div>
          </div>
          <div className={style.partner}>
            <div>
              <div className={style.arow}>
                <Image className={style.move} src='/a.png' width='85px' height='97px'/>
              </div>
              <p className={style.sm_para}>Scheibye-Knudsen Lab </p>
              <p className={style.para}>Research Partner</p>
              <div className={style.arrow_left}>
                <Image src='/earrow.png' width='15px' height='15px'/>
              </div>
              <hr className={style.bm_hr}/>
            </div>
          </div>
          <div className={style.partner}>
            <div>
              <div className={style.arow}>
                <Image src='/a.png' width='85px' height='97px'/>
              </div>
              <p className={style.sm_para}>Scheibye-Knudsen Lab </p>
              <p className={style.para}>Research Partner</p>
              <div className={style.arrow_left}>
                  <Image src='/earrow.png' width='15px' height='15px'/>
              </div>
              <hr className={style.bm_hr}/>
              <p className={style.p}>See all</p>
              <hr className={style.pi}/>
            </div>
          </div>
        </div>
        <p className={style.h2}>FEATURED PROJECT</p>
      </section>
      <section className={style.waste}>
        <div className={style.bg_waste}>
          <h1>Wastewater to cheap <br/>  electricity </h1>
          <div className={style.sm_waste}>
            <div className={style.sm_option}><p>Validated</p></div>
            <div className={style.sm_option}><p>Funded</p></div>
            <div className={style.sm_option}><p>On-going</p></div>
          </div>
          <p>The global microbial fuel cell market is expected to grow from about $ 9.0 million in 2017 to $ 18.6 million in 2025, at a CAGR of 9.5% from 2017 to 2025. </p>
          <p>Our unique solution uses a combination of microbial fuel and electrolytic cells to produce green hydrogen from wastewater. </p>
          <div className={style.funding}>
            <div className={style.bg_funding}>
              <h5>FUNDING</h5>
              <p>$ 200,000.00</p>
              <hr/>
            </div>
            <div className={style.bg_funding}>
              <h5>BACKERS</h5>
              <p>50 contributors</p>
              <hr/>
            </div>
            <div>
              <p className={style.website}>Visit website <Image className={style.Image} src="/earrow.png" width="10.37px" height="10.27px"/></p>
              <hr className={style.main_hr}/>
            </div>
          </div>
          <div className={style.bg_website}>
            <div><Image src='/leftArrow.png' width='34px' height='34px'/></div>
            <div><Image src='/rightArrow.png' width='34px' height='34px'/></div>
          </div>
        </div>
        <div className={style.pg_overlay}></div>
      </section>
      <section className={style.bg_news_section}>
        <h1 className={style.bg_news_section_h1}>News and Stories</h1>
        <div>
          <div className={style.sm_news_section}>
            <div className={style.new_section}>
              <h1>News Story Article Name</h1>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam. Ut enim ad minim/</p>
              <p className={style.news_read}>Read More</p>
              <hr/>
            </div>
            <div className={style.news_section}>
              <h1>News Story Article Name</h1>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam. Ut enim ad minim/</p>
              <p className={style.news_read}>Read More</p>
              <hr/>
            </div>
            <hr/>
            <div className={style.news_section}>
              <h1>News Story Article Name</h1>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam. Ut enim ad minim/</p>
              <p className={style.news_read}>Read More</p>
              <hr/>
            </div>
            <hr/>
          </div>
          <div className={style.darkarrow}>
            <div className={style.transform}><Image src='/darkarrow1.png' width='42px' height='42px'/></div>
            <div><Image src='/darkarrow1.png' width='42px' height='42px'/></div>
          </div>
        </div>
      </section>
      <section className={style.changing_world}>
        <div>
        <h1>Be a part of changing the world</h1>
        <p>Keep energy researches afloat with us as we build a future for context-based energy in emerging markets</p>
        <div className={style.changing_world_img}>
          <div><Image src='/discord.png' height='46px' width='44px'/></div>
          <div><Image src='/telegram.png' height='46px' width='44px'/></div>
          <div><Image src='/medium.png' height='46px' width='44px'/></div>
          <div><Image src='/youtube.png' height='46px' width='44px'/></div>
          <div><Image src='/twitter.png' height='46px' width='44px'/></div>
        </div>
        </div>
      </section>
    <Footer/>
    </div>
  )
}

export default Home
