import type { NextPage } from 'next'
import Link from 'next/link'
import Head from 'next/head'
import Image from 'next/image'
import style from '../styles/Home.module.css'
import Navbar from '../components/external/Navbar'
import Footer from '../components/external/Footer'

const Lab: NextPage = () => {
  return (
    <>
      <Navbar />
      <header>
        <div className={style.header3}>
          <p className={style.product_para}>PRODUCT</p>
          <h1>Kayce Labs</h1>
          <p>
            At Kayce labs, we carry out research projects to provide the
            technological infrastructures for accelerating the energy transition
            in emerging countries. Our approach includes conducting research,
            design and development and implementing an emerging country
            technology strategy
          </p>
          <div>
            <Link href="/">
              <a className={style.link2}>
                <span>Learn More</span>
                <hr className={style.sec_hr2} />
              </a>
            </Link>
          </div>
        </div>
        <div className={style.sec_image}>
          <Image src="/KL.png" width="525px" height="682px" />
        </div>
      </header>
      <section>
        <div className={style.ls_section}>
          <h1>
            We are building the largest open innovation challenge in the world
            to accelerate electrification in emerging economies
          </h1>
          <p>
            Kayce Labs empowers billions of people by creating access to
            electricity with an inclusive, scalable and sustainable model. We
            explore how to innovate the way energy is produced, distributed and
            consumed in emerging markets so that each individual has better
            access to electricity.
          </p>
        </div>
      </section>
      <section>
        <div className={style.conatiner_section}>
          <div className={style.section_head}>
            <h1>
              We are building the largest open innovation challenge in the world
              to accelerate electrification in emerging economies
            </h1>
          </div>
          <div className={style.h_div}></div>
          <div className={style.sm_container_section}>
            <p>
              We are taking a multi-faceted approach to supporting energy
              research by building the world’s largest open innovation challenge
              to increase electrification rates in rural communities. In doing
              this, we are making a difference for disadvantaged emerging
              economies by accelerating the timeline for the most suitable
              contexualized electrification.{' '}
            </p>
          </div>
        </div>
      </section>
      <div>
        <Image src="/Frame161.png" width="1440px" height="115px" />
      </div>
      <section className={style.portfolio}>
        <div className={style.portfolio_image}>
          <Image src="/KL_portfolio.png" width="488px" height="566px" />
        </div>
        <div className={style.portfolio_body}>
          <p>
            <span>
              We are building the largest open innovation challenge in the world
            </span>{' '}
            to accelerate rural electrification in emerging economies with
            distributed renewables.
          </p>
          <p>
            Our mission is to develop, share and disseminate cutting edge green
            technologies fitting for contexts in emerging countries.
          </p>

          <h3>PORTFOLIO STRUCTURE</h3>
          <p>
            VitaDAO will acquire and commission research, as well as own,
            develop and monetize the resulting intellectual property assets. Our
            portfolio consists of:
          </p>
          <p>
            1. NFTs representing intellectual property, patents and licenses to
            therapeutic research projects.
          </p>
          <p>
            2. Data assets generated by funding R&D around its research projects
            and NFTs.
          </p>
          <p>
            To fund more research and to provide long term funding for the DAO
            operations, there are several options to monetize owned data and IP
          </p>

          <h3>RAPID AND COMMERCIALLY VIABLE</h3>
          <p>
            <span>
              Hosted on a custom platform built and operated by Kayce DAO
            </span>{' '}
            to rapidly discover and commercialize techniques for inexpensive,
            safe and reliable electricity generation in emerging economies. The
            goal of the Open Electrification Challenge is to accelerate
            market-based solutions for rural electrification with the aim of
            increasing access to electricity worldwide.
          </p>
          <p>
            Do you work on novel technologies to enable renewable energy
            production for rural economies? Or technologies without carbon
            emissions as well as green technologies that lead to more efficent
            utilization of energy in unpopular markets? Then we are inviting you
            to be a part of our open challenge.
          </p>
          <Link href="/">
            <a className={style.link7}>
              <span>Apply for funding</span>
              <hr className={style.sec_hr7} />
            </a>
          </Link>
        </div>
      </section>
      <hr className={style.sec_hr8} />
      <section className={style.big_news_section}>
        <h1 className={style.big_news_section_h1}>OUR FOCUS AREA</h1>
        <div className={style.parent_div}>
          <div className={style.sm_news_section}>
            <div className={style.new_section2}>
              <h1>1</h1>
              <h1>Social Energy Networks</h1>
              <p>
                Design of social and community energy networks that decouple
                end-user consumption from the grid and business models that
                enable them.
              </p>
            </div>
            <div className={style.news_section2}>
              <h1>2</h1>
              <h1>Wireless Energy Distribution</h1>
              <p>
                How wireless power-sharing can be implemented with existing
                telecom operators or blockchain companies like Helium for
                microgrids and mesh networks deployed in developing countries.
              </p>
            </div>
            <div className={style.news_section2}>
              <h1>3</h1>
              <h1>Next Generation Energy Storage:</h1>
              <p>
                Creating a framework for circular battery economy, leading to
                cheaper microgrids and energy systems in emerging markets{' '}
              </p>
            </div>
          </div>
        </div>
      </section>
      <section className={style.big_news_section}>
        <h1 className={style.big_news_section_h1}>GRANTS/PROJECTS</h1>
        <div className={style.parent_div}>
          <div className={style.sm_news_section}>
            <div className={style.news_section3}>
              <h1>Grant/Project Name</h1>
              <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
                enim ad minim veniam. Ut enim ad minim/
              </p>
              <div className={style.news_div_section3}>
                <div>
                  <Link href="/">
                    <a className={style.link6}>
                      <span>Join Grant</span>
                      <hr className={style.sec_hr6} />
                    </a>
                  </Link>
                </div>
                <div className={style.sec_image}>
                  <Image src="/Frame98.png" width="13px" height="13px" />
                </div>
              </div>
            </div>
            <div className={style.news_section2}>
              <h1>Grant/Project Name</h1>
              <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
                enim ad minim veniam. Ut enim ad minim/
              </p>
              <div className={style.news_div_section3}>
                <div>
                  <Link href="/">
                    <a className={style.link6}>
                      <span>Join Grant</span>
                      <hr className={style.sec_hr6} />
                    </a>
                  </Link>
                </div>
                <div className={style.sec_image}>
                  <Image src="/Frame98.png" width="13px" height="13px" />
                </div>
              </div>
            </div>
            <div className={style.news_section2}>
              <h1>Grant/Project Name</h1>
              <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
                enim ad minim veniam. Ut enim ad minim/
              </p>
              <div className={style.news_div_section3}>
                <div>
                  <Link href="/">
                    <a className={style.link6}>
                      <span>Join Grant</span>
                      <hr className={style.sec_hr6} />
                    </a>
                  </Link>
                </div>
                <div className={style.sec_image}>
                  <Image src="/Frame98.png" width="13px" height="13px" />
                </div>
              </div>
            </div>
          </div>
          <div className={style.darkarrow}>
            <div className={style.transform}>
              <Image src="/darkarrow1.png" width="42px" height="42px" />
            </div>
            <div>
              <Image src="/darkarrow1.png" width="42px" height="42px" />
            </div>
          </div>
        </div>
      </section>
      <section className={style.bg_container_we}>
        <h1>We are looking for you if</h1>
        <p>
          you are interested in setting up clean energy networks, storage
          technologies and facilities in emerging markets with the goal of
          supporting incomes, security and environmental sustainability in
          places that need it most.
        </p>
        <Link href="/">
          <a className={style.link7}>
            <span>Apply for funding</span>
            <hr className={style.sec_hr9} />
          </a>
        </Link>
      </section>
      <Footer />s
    </>
  )
}

export default Lab
