import type { NextPage } from 'next'
import Link from 'next/link'
import Head from 'next/head'
import Image from 'next/image'
import style from '../styles/Home.module.css'
import Navbar from '../components/external/Navbar'
import Footer from '../components/external/Footer'

const Product: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <header>
        <div className={style.header2}>
          <p className={style.product_para}>PRODUCT</p>
          <h1>Zero Gate Wallet </h1>
          <p>
            is a trustless platform that accelerates impactful asset allocation
            by connecting investors with opportunities for green investment that
            are immutably verified for impact.
          </p>
          <div>
            <Link href="/">
              <a className={style.link2}>
                <span>Apply for funding</span>
                <hr className={style.sec_hr2} />
              </a>
            </Link>
          </div>
        </div>
        <div className={style.sec_image}>
          <Image src="/ZGW.png" width="267px" height="677.3px" />
        </div>
      </header>
      <section>
        <div className={style.ls_section}>
          <h1>
            We’re reimagining energy financing so every growing energy company
            can realize their full potential.
          </h1>
          <p>We provide the infrastructure for energy systems in Africa</p>
        </div>
      </section>
      <section>
        <div className={style.conatiner_section}>
          <div className={style.section_head}>
            <h1>
              Build the future of sustainable energy research financing with us
            </h1>
          </div>
          <div className={style.h_div}></div>
          <div className={style.sm_container_section}>
            <p>
              Zero Gate Wallet provides financing for sustainable green energy
              companies and projects by de-risking investment in such projects
              and serving as the middle man between VCs and consumer equity
              financers through decentralised banking models.
            </p>
          </div>
        </div>
      </section>
      <div className={style.mid}>
        <Image src="/mid.png" width="1440px" height="122.76px" />
      </div>
      <section>
        <p className={style.container_bg_important_p}>WHY IS THIS IMPORTANT?</p>
        <div className={style.container_bg_important}>
          <div className={style.main_container_bg_important}>
            <div className={style.main_container_bg_important_div}>
              <h1>70-85% </h1>
              <p>
                of world's energy supply should be powered by renewable energy
                in 2050
              </p>
            </div>
            <div className={style.main_container_bg_important_div}>
              <h1>4-10x</h1>
              <p>
                more financial investments needed compared to 2015 in renewable
                technologies to limit climate change{' '}
              </p>
            </div>
            <div className={style.main_container_bg_important_div}>
              <h1>$59.5b</h1>
              <p>
                invested in emerging countries (excl. CHINA and India) in 2019
                alone.
              </p>
            </div>
          </div>
          <div className={style.main_container_bg_important}>
            <div>
              <hr />
            </div>
            <div>
              <h3>HOWEVER</h3>
            </div>
            <div>
              <hr />
            </div>
          </div>
          <div className={style.main_container_bg_important}>
            <div className={style.main_container_bg_important_div}>
              <h1>26%</h1>
              <p>
                chance of making profit off a standard microgrid installment in
                emerging countries{' '}
              </p>
            </div>
            <div className={style.main_container_bg_important_div}>
              <h1>-20%</h1>
              <p>
                Annual investments across all parts of the energy sector in
                emerginG markets have fallen by around 20% since 2016
              </p>
            </div>
            <div className={style.main_container_bg_important_div}>
              <h1>7x</h1>
              <p>
                Because of dwindling interest, emerging countries face 7 times
                more equity costs and debt than the US or europe
              </p>
            </div>
          </div>
        </div>
      </section>
      <section>
        <div className={style.container_bank}>
          <div className={style.container_bank_h1}>
            <h1>
              The ‘bank’ powering the energy transition in emerging markets
            </h1>
          </div>
          <div className={style.container_bank_p}>
            <p>
              Financing the energy sector in emerging markets has traditionally
              been provided by grantmakers, impact investors, and development
              finance institutions (mostly in the form of grant and debt
              facilities). These sources of financing have been essential to
              nurture and launch the sector. They will be insufficient to scale
              the sector to its potential. Bringing the sector to scale will
              require greater participation from commercial equity and debt
              investors
            </p>
          </div>
        </div>
      </section>

      <section className={style.big_news_section}>
        <h1 className={style.big_news_section_h1}>SERVICES</h1>
        <div className={style.parent_div}>
          <div className={style.sm_news_section}>
            <div className={style.new_section}>
              <h1>Project Financing</h1>
              <p>
                Apply for funding from KayceDAO with a research or energy
                start-up that is focused on developing green and sustainable
                energy for emerging countries and economies. Read our FAQs and
                criteria to find out if your company, project or research
                qualify.
              </p>
            </div>
            <div className={style.news_section}>
              <h1>Financial Services</h1>
              <p>
                We provide services like{' '}
                <span className={style.bold}>
                  collections, portfolio management, liability managent and
                  insurance and loans
                </span>{' '}
                for green tech startups as well as established energy tech
                businesses in emerging markets.
              </p>
            </div>
            <div className={style.news_section}>
              <h1>Energy Trading</h1>
              <p>
                Have big dreams to implement new energy systems? Want to connect
                your networks to global participants who pay for your services
                for carbon credit NFTs? We have you covered!
              </p>
            </div>
          </div>
          <div className={style.sm_news_section1}>
            <div className={style.news_section1}>
              <h1 className={style.news_section_h}>
                Decentralized <br />
                Green Bonds
              </h1>
              <p>
                As a sustainable energy investment focused DAO, we make
                available to you the opportunity to finance projects for a
                sustainble tomorrow with reduced risk and reliable expected
                returns.
              </p>
            </div>
            <div className={style.news_section}>
              <h1 className={style.news_section_h}>Carbon credit finance</h1>
              <p>
                We offer private companies a safe route for trading extra
                credits and topping up credits, with added higher returns on
                traded credits to incentivise the reduction of greenhouse
                emmissions.
              </p>
            </div>
            <div className={style.news_section}>
              <h1 className={style.news_section_h}>
                Inflation / <br />
                Currency Hedging
              </h1>
              <p>
                We de-complicate the complexity of currency mismatch in local
                currency repayments and hard currency input costs by financing
                capital and investments with our blockchain token system,
                setting a measurable standard for output and revenue.
              </p>
            </div>
          </div>
          <div className={style.big_image}>
            <Image src="/pattern1.png" width="174.8px" height="455.04px" />
          </div>
        </div>
      </section>
      <section className={style.bg_container_ready}>
        <div className={style.container_ready}>
          <div className={style.container_ready_hr}>
            <h1>Ready to make a move?</h1>
            <p>
              Join our DAO to get contribute to the future of energy research or
              begin your application process for funding as an energy research
              or start-up that matches our criteria
            </p>
          </div>
          <div className={style.ready_link}>
            <Link href="/">
              <a>
                <span className={style.a_link}>Join Us</span>
                <hr className={style.main_hr} />
              </a>
            </Link>
          </div>
          <div className={style.ready_link}>
            <Link href="/">
              <a>
                <span className={style.main}>
                  Apply for Funding
                  <Image
                    className={style.Image}
                    src="/pinkarrow.png"
                    width="14.87px"
                    height="14.87px"
                  />
                </span>
                <hr className={style.main_hr1} />
              </a>
            </Link>
          </div>
        </div>
      </section>
      <section className={style.container_limitation}>
        <h1>No more limitations, change the world with us by your side!</h1>
        <div className={style.bg_container_limitation}>
          <div className={style.bg_main_container_limitation}>
            <h3>When we work with you, we win more together!</h3>
            <p>
              Solving the clean energy puzzle is crucial for millions of people
              globally. The problem is complex and requires organizations and
              actors to work together.
            </p>
          </div>
          <div className={style.sm_container_limitation}>
            <div className={style.sm_img_container_limitation}>
              <div className={style.sm_header_container_limitation}>
                <h3>The world’s main fuel supply is running out!</h3>
                <p>
                  With the world's supply of fossil fuels on track to be
                  depleted within 30 years, determining how to invest in
                  alternative energy is no longer a question of if, but when.
                </p>
              </div>
              <span
                className={style.sm_header_overlay_container_limitation}
              ></span>
              <div className={style.sm_header_img_container_limitation}>
                <Image src="/pexels.png" width="274px" height="242px" />
              </div>
            </div>
            <div className={style.sm_img_1_container_limitation}>
              <div className={style.sm_header_1_container_limitation}>
                <h3>Getting your voice heard has never been this easier!</h3>
                <p>
                  Collaborate with and make decisions alongside future leading
                  companies and current global energy research in developing
                  innovative energy solutions for emerging markets.
                </p>
              </div>
              <div className={style.sm_header_1_img_container_limitation}></div>
            </div>
          </div>
        </div>
      </section>
      <section className={style.bg_portfolio_container}>
        <h1 className={style.bg_a_portfolio_container}>
          PORTFOLIO COMPANIES / PROJECTS
        </h1>
        <div className={style.bg_main_portfolio_container}>
          <div className={style.sm_main_portfolio_container}>
            <div className={style.portfolio_container}>
              <p>
                Molecule is a startup which does yada and yada and we believe
                they are the best thing since sliced bread because reasons
              </p>
              <hr className={style.hr1_portfolio_container} />
            </div>
            <div className={style.main_portfolio_container}>
              <div className={style.main_img_portfolio_container}>
                <Image src="/Frame.png" width="123px" height="113px" />
              </div>
              <p className={style.main_p_portfolio_container}>Molecule</p>
              <p className={style.sm_p_portfolio_container}>Startup</p>
              <div className={style.left_portfolio_container}>
                <Image src="/smArrow.png" width="15px" height="15px" />
              </div>
              <hr className={style.hr_portfolio_container} />
            </div>
            <div className={style.small_portfolio_container}>
              <p className={style.main_p_portfolio_container}>
                Scheibye-Knudsen Lab
              </p>
              <p className={style.sm_p_portfolio_container}>Research Partner</p>
              <div className={style.left_portfolio_container}>
                <Image src="/smArrow.png" width="15px" height="15px" />
              </div>
              <hr className={style.hr_portfolio_container} />
            </div>
            <div className={style.small_portfolio_container}>
              <p className={style.main_p_portfolio_container}>
                Scheibye-Knudsen Lab
              </p>
              <p className={style.sm_p_portfolio_container}>Research Partner</p>
              <div className={style.left_portfolio_container}>
                <Image src="/smArrow.png" width="15px" height="15px" />
              </div>
              <hr className={style.hr_portfolio_container} />
            </div>
            <div className={style.small_portfolio_container}>
              <p className={style.main_p_portfolio_container}>
                Scheibye-Knudsen Lab
              </p>
              <p className={style.sm_p_portfolio_container}>Research Partner</p>
              <div className={style.left_portfolio_container}>
                <Image src="/smArrow.png" width="15px" height="15px" />
              </div>
              <hr className={style.hr_portfolio_container} />
            </div>
          </div>
          <div className={style.sm_main_portfolio_container}>
            <div className={style.small_portfolio_container}>
              <p className={style.main_p_portfolio_container}>
                Scheibye-Knudsen Lab
              </p>
              <p className={style.sm_p_portfolio_container}>Research Partner</p>
              <div className={style.left_portfolio_container}>
                <Image src="/smArrow.png" width="15px" height="15px" />
              </div>
              <hr className={style.hr_portfolio_container} />
            </div>
            <div className={style.main_portfolio_container}>
              <div className={style.main_img_portfolio_container}>
                <Image src="/Frame.png" width="123px" height="113px" />
              </div>
              <p className={style.main_p_portfolio_container}>Molecule</p>
              <p className={style.sm_p_portfolio_container}>Startup</p>
              <div className={style.left_portfolio_container}>
                <Image src="/smArrow.png" width="15px" height="15px" />
              </div>
              <hr className={style.hr_portfolio_container} />
            </div>
            <div className={style.small_portfolio_container}>
              <p className={style.main_p_portfolio_container}>
                Scheibye-Knudsen Lab
              </p>
              <p className={style.sm_p_portfolio_container}>Research Partner</p>
              <div className={style.left_portfolio_container}>
                <Image src="/smArrow.png" width="15px" height="15px" />
              </div>
              <hr className={style.hr_portfolio_container} />
            </div>
            <div className={style.small_portfolio_container}>
              <p className={style.main_p_portfolio_container}>
                Scheibye-Knudsen Lab
              </p>
              <p className={style.sm_p_portfolio_container}>Research Partner</p>
              <div className={style.left_portfolio_container}>
                <Image src="/smArrow.png" width="15px" height="15px" />
              </div>
              <hr className={style.hr_portfolio_container} />
            </div>
            <div className={style.small_portfolio_container}>
              <p className={style.main_p_portfolio_container}>
                Scheibye-Knudsen Lab
              </p>
              <p className={style.sm_p_portfolio_container}>Research Partner</p>
              <div className={style.left_portfolio_container}>
                <Image src="/smArrow.png" width="15px" height="15px" />
              </div>
              <hr className={style.hr_portfolio_container} />
            </div>
          </div>
        </div>
      </section>
      <section className={style.bg_portfolio_container}>
        <h1 className={style.bg_h_portfolio_container}>PARTNERS</h1>
        <div className={style.bg_main_portfolio_container}>
          <div className={style.sm_main_portfolio_container}>
            <div className={style.mn_portfolio_container}>
              <p>
                Sneider Electric is a multi-national company focusing on
                electric vehicles, finaincing and yada yada. They are more than
                happy to work with Kayce because we are the best.
              </p>
              <hr className={style.hr2_portfolio_container} />
            </div>
            <div className={style.main_portfolio_container}>
              <div className={style.main_img_portfolio_container}>
                <Image src="/Frame.png" width="123px" height="113px" />
              </div>
              <p className={style.main_p_portfolio_container}>Molecule</p>
              <p className={style.sm_p_portfolio_container}>Startup</p>
              <div className={style.left_portfolio_container}>
                <Image src="/smArrow.png" width="15px" height="15px" />
              </div>
              <hr className={style.hr_portfolio_container} />
            </div>
            <div className={style.small_portfolio_container}>
              <p className={style.main_p_portfolio_container}>
                Scheibye-Knudsen Lab
              </p>
              <p className={style.sm_p_portfolio_container}>Research Partner</p>
              <div className={style.left_portfolio_container}>
                <Image src="/smArrow.png" width="15px" height="15px" />
              </div>
              <hr className={style.hr_portfolio_container} />
            </div>
            <div className={style.small_portfolio_container}>
              <p className={style.main_p_portfolio_container}>
                Scheibye-Knudsen Lab
              </p>
              <p className={style.sm_p_portfolio_container}>Research Partner</p>
              <div className={style.left_portfolio_container}>
                <Image src="/smArrow.png" width="15px" height="15px" />
              </div>
              <hr className={style.hr_portfolio_container} />
            </div>
            <div className={style.small_portfolio_container}>
              <p className={style.main_p_portfolio_container}>
                Scheibye-Knudsen Lab
              </p>
              <p className={style.sm_p_portfolio_container}>Research Partner</p>
              <div className={style.left_portfolio_container}>
                <Image src="/smArrow.png" width="15px" height="15px" />
              </div>
              <hr className={style.hr_portfolio_container} />
            </div>
          </div>
        </div>
      </section>
      <section className={style.bg_economy}>
        <div className={style.main_bg_economy}>
          <h1>A green economy is a smarter economy</h1>
          <p>
            And with the world's supply of fossil fuels on track to be depleted
            within 30 years, determining how to invest in alternative energy is
            no longer a question of if, but when.
          </p>
          <Link href="/">
            <a>
              <span className={style.link5}>Apply for funding</span>
              <hr className={style.sec_hr5} />
            </a>
          </Link>
        </div>
        <div className={style.img_bg_economy}>
          <div>
            <Image src="/orange_discord.png" width="44px" height="46px" />
          </div>
          <div>
            <Image src="/orangeTelegram.png" width="43px" height="46px" />
          </div>
          <div>
            <Image src="/orangemedium.png" width="54px" height="53px" />
          </div>
          <div>
            <Image src="/orangeyoutube.png" width="51px" height="46px" />
          </div>
          <div>
            <Image src="/orangetwitter.png" width="47px" height="45px" />
          </div>
        </div>
      </section>
      <Footer/>
    </div>
  )
}

export default Product
